services:
  php:
    build:
      context: .
      dockerfile: ./deployment/local/php-fpm/Dockerfile
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    depends_on:
      - php
    volumes:
      - ./deployment/local/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    ports:
      - "8080:80"

  db:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./deployment/local/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:
